sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t keratin/authn .

script:
  - docker run -e SECRET_KEY_BASE=notsosecret
               -e APP_DOMAINS=example.com
               -e HTTP_AUTH_USERNAME=hello
               -e HTTP_AUTH_PASSWORD=world
               -e AUTHN_URL=http://auth.dev
              keratin/authn
              bin/rails test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push keratin/authn;
    fi
