sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t keratin/authn .

script:
  - docker-compose run test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push keratin/authn;
    fi
