module ErrorCodes
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED'
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND'
  CREDENTIALS_FAILED = 'CREDENTIALS_FAILED'
  PASSWORD_INSECURE = 'PASSWORD_INSECURE'
  PASSWORD_MISSING = 'PASSWORD_MISSING'
  TOKEN_INVALID_OR_EXPIRED = 'TOKEN_INVALID_OR_EXPIRED'
  USERNAME_MISSING = 'USERNAME_MISSING'
  USERNAME_TAKEN = 'USERNAME_TAKEN'
  FORMAT = 'FORMAT_INVALID'
end
