module ErrorCodes
  FAILED = 'FAILED'
  FORMAT_INVALID = 'FORMAT_INVALID'
  INSECURE = 'INSECURE'
  INVALID_OR_EXPIRED = 'INVALID_OR_EXPIRED'
  LOCKED = 'LOCKED'
  MISSING = 'MISSING'
  NOT_FOUND = 'NOT_FOUND'
  TAKEN = 'TAKEN'
  EXPIRED = 'EXPIRED'
end
