default: &default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS'){ 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  url: sqlite3:db/test.sqlite3
